version: "3.6"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - supinfo
  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    networks:
      - supinfo
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - '8000:8081'
      networks:
        - supinfo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


volumes:
  mongo_data:
    name: "5-data-mongo-database"
    driver: local


networks:
  supinfo:
    external: true