version: "3.6"
services:
  mongo:
    hostname: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
      - ../app/samples:/samples
      - ../app/import.sh:/seed/import.sh
    networks:
      - 5data-overlay
    ports:
      - "27017:27017"
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - '8000:8081'
      networks:
        - 5data-overlay
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      deploy:
        replicas: 1

volumes:
  mongo_data:
    name: "5-data-mongo-database"
    driver: local


networks:
  5data-overlay:
    driver: overlay
    external: true