version: '3.6'

services:
  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
      - 4141:4141
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"


  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
      image: andreper/spark-worker:3.0.0
      container_name: spark-worker-1
      environment:
        - SPARK_WORKER_CORES=8
        - SPARK_WORKER_MEMORY=8g
      ports:
        - 8081:8081
      volumes:
        - shared-workspace:/opt/workspace
      depends_on:
        - spark-master

  spark-worker-2:
      image: andreper/spark-worker:3.0.0
      container_name: spark-worker-2
      environment:
        - SPARK_WORKER_CORES=4
        - SPARK_WORKER_MEMORY=8g
      ports:
        - 8082:8081
      volumes:
        - shared-workspace:/opt/workspace
      depends_on:
        - spark-master

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
