version: "3.6"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - '8000:8081'
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
      image: andreper/spark-worker:3.0.0
      container_name: spark-worker-1
      environment:
        - SPARK_WORKER_CORES=1
        - SPARK_WORKER_MEMORY=512m
      ports:
        - 8081:8081
      volumes:
        - shared-workspace:/opt/workspace
      depends_on:
        - spark-master
  spark-worker-2:
      image: andreper/spark-worker:3.0.0
      container_name: spark-worker-2
      environment:
        - SPARK_WORKER_CORES=1
        - SPARK_WORKER_MEMORY=512m
      ports:
        - 8082:8081
      volumes:
        - shared-workspace:/opt/workspace
      depends_on:
        - spark-master

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  mongo_data:
    name: "5-data-mongo-database"
    driver: local